import { TanstackProvider } from "@/src/components/providers/tanstack-providers"
import type { Metadata } from "next"
import { Inter, Mansalva, Mogra, Space_Grotesk } from "next/font/google"
import { Toaster } from "sonner"
import "./globals.css"

const inter = Inter({
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
})

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
})

const mansalva = Mansalva({
  variable: "--font-mansalva",
  weight: ["400"],
  subsets: ["latin"],
})

const mogra = Mogra({
  variable: "--font-mogra",
  weight: ["400"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} ${mansalva.variable} ${mogra.variable}`}
      >
        <Toaster richColors />
        <TanstackProvider> {children}</TanstackProvider>
      </body>
    </html>
  )
}
